const { PrismaClient } = require("@prisma/client");
const bcrypt = require("bcryptjs");

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding database...");

  // Clean existing data
  await prisma.returnRequest.deleteMany({});
  await prisma.settlement.deleteMany({});
  await prisma.orderItem.deleteMany({});
  await prisma.order.deleteMany({});
  await prisma.inquiry.deleteMany({});
  await prisma.product.deleteMany({});
  await prisma.category.deleteMany({});
  await prisma.address.deleteMany({});
  await prisma.user.deleteMany({});

  // Seed Admin User
  const adminEmail = process.env.ADMIN_EMAIL || "admin@stopshop.com";
  const adminPassword = process.env.ADMIN_PASSWORD || "admin123";
  const hashedAdminPassword = await bcrypt.hash(adminPassword, 10);
  const admin = await prisma.user.create({
    data: {
      name: "Admin StopShop",
      email: adminEmail,
      password: hashedAdminPassword,
      role: "admin",
    },
  });
  console.log(`Admin seeded (${adminEmail})`);

  // Seed Vendor User
  const hashedVendorPassword = await bcrypt.hash("vendor123", 10);
  const vendor = await prisma.user.create({
    data: {
      name: "Moradabad Artisans Hub",
      email: "vendor@stopshop.com",
      password: hashedVendorPassword,
      role: "vendor",
    },
  });
  console.log("Vendor seeded (vendor@stopshop.com)");

  // Seed Categories
  const categories = [
    { name: "Kitchen Utility", slug: "kitchen-utility", image: "/bronze-kadai.png" },
    { name: "Brass Cookware", slug: "brass-cookware", image: "/collection-tableware.png" },
    { name: "Pooja Collection", slug: "pooja-collection", image: "/collection-pooja.png" },
    { name: "Copper Products", slug: "copper-products", image: "/bronze-lota.png" },
    { name: "Steel Essentials", slug: "steel-essentials", image: "/bronze-kadai.png" },
    { name: "Home Living", slug: "home-living", image: "/collection-pooja.png" },
    { name: "Bedroom Essentials", slug: "bedroom-essentials", image: "/collection-tableware.png" },
    { name: "Living Room", slug: "living-room", image: "/collection-pooja.png" },
    { name: "Handicrafts", slug: "handicrafts", image: "/collection-pooja.png" },
    { name: "Kitchen Racks", slug: "kitchen-racks", image: "/bronze-kadai.png" },
    { name: "Dinner Sets", slug: "dinner-sets", image: "/collection-tableware.png" },
  ];

  for (const cat of categories) {
    await prisma.category.create({ data: cat });
  }
  console.log("Categories seeded");

  // Mock Products list to insert
  const products = [
    // 12 Products for Kitchen Utility
    {
      name: "Heritage Bronze Kadai",
      slug: "heritage-bronze-kadai",
      description: "Heavy-duty pure bronze cooking kadai, hand-beaten by traditional coppersmiths for uniform heating.",
      specs: "Weight: 2.4 kg | Hand-Hammered",
      image: "/bronze-kadai.png",
      images: JSON.stringify(["/bronze-kadai.png", "/bronze-hero.png"]),
      price: 2499,
      mrp: 3199,
      discount: 22,
      rating: 4.9,
      reviews: 124,
      categoryName: "kitchen-utility",
      material: "Bronze",
      featured: true,
      stock: 5,
      vendorId: vendor.id
    },
    {
      name: "Handcrafted Bronze Handi",
      slug: "handcrafted-bronze-handi",
      description: "Elegant deep-cooking pot with lid, perfect for slow-cooking curries and biryanis.",
      specs: "Capacity: 3 Litres | Heavy Bottom",
      image: "/bronze-hero.png",
      images: JSON.stringify(["/bronze-hero.png"]),
      price: 3299,
      mrp: 4499,
      discount: 27,
      rating: 4.7,
      reviews: 67,
      categoryName: "kitchen-utility",
      material: "Bronze",
      featured: true,
      stock: 3,
      vendorId: vendor.id
    },
    {
      name: "Classic Bronze Patila",
      slug: "classic-bronze-patila",
      description: "Flat-bottomed classic cooking vessel designed for day-to-day culinary needs.",
      specs: "Weight: 1.8 kg | Pure Bronze",
      image: "/bronze-hero.png",
      images: JSON.stringify(["/bronze-hero.png"]),
      price: 1999,
      mrp: 2699,
      discount: 26,
      rating: 4.8,
      reviews: 73,
      categoryName: "kitchen-utility",
      material: "Bronze",
      featured: true,
      stock: 8,
      vendorId: null
    },
    {
      name: "Vintage Brass Spice Box",
      slug: "vintage-brass-spice-box",
      description: "Traditional kitchen spice box handcrafted in brass with 7 individual compartments for essential spices.",
      specs: "Material: Brass | 7 Compartments",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 1499,
      mrp: 1999,
      discount: 25,
      rating: 4.8,
      reviews: 92,
      categoryName: "kitchen-utility",
      material: "Brass",
      featured: false,
      stock: 12,
      vendorId: vendor.id
    },
    {
      name: "Traditional Brass Milk Can",
      slug: "traditional-brass-milk-can",
      description: "Exquisite traditional milk storage container with airtight lid and handle.",
      specs: "Capacity: 2 Litres | Pure Brass",
      image: "/bronze-kadai.png",
      images: JSON.stringify(["/bronze-kadai.png"]),
      price: 1899,
      mrp: 2499,
      discount: 24,
      rating: 4.7,
      reviews: 43,
      categoryName: "kitchen-utility",
      material: "Brass",
      featured: false,
      stock: 15,
      vendorId: null
    },
    {
      name: "Hand-Hammered Brass Urli",
      slug: "hand-hammered-brass-urli",
      description: "Ornate brass bowl widely used for cooking or as an aesthetic centerpiece filled with water and flowers.",
      specs: "Diameter: 12 Inches | Weight: 2 kg",
      image: "/collection-pooja.png",
      images: JSON.stringify(["/collection-pooja.png"]),
      price: 2199,
      mrp: 2999,
      discount: 27,
      rating: 4.9,
      reviews: 110,
      categoryName: "kitchen-utility",
      material: "Brass",
      featured: true,
      stock: 7,
      vendorId: vendor.id
    },
    {
      name: "Premium Copper Water Bottle Utility",
      slug: "premium-copper-water-bottle-utility",
      description: "Health-focused leakproof pure copper water bottle for everyday kitchen utility.",
      specs: "Capacity: 1 Litre | Joint-less",
      image: "/bronze-lota.png",
      images: JSON.stringify(["/bronze-lota.png"]),
      price: 999,
      mrp: 1399,
      discount: 29,
      rating: 4.9,
      reviews: 134,
      categoryName: "kitchen-utility",
      material: "Copper",
      featured: false,
      stock: 25,
      vendorId: vendor.id
    },
    {
      name: "Copper Infused Serving Spoons",
      slug: "copper-infused-serving-spoons",
      description: "Set of 4 pure copper serving and cooking spoons designed to enhance food presentation.",
      specs: "Set of 4 | Pure Copper",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 799,
      mrp: 1099,
      discount: 27,
      rating: 4.6,
      reviews: 58,
      categoryName: "kitchen-utility",
      material: "Copper",
      featured: false,
      stock: 20,
      vendorId: null
    },
    {
      name: "Heavy-Gauge Steel Kadai",
      slug: "heavy-gauge-steel-kadai",
      description: "Highly durable rust-resistant stainless steel cooking kadai with double handles.",
      specs: "Weight: 1.5 kg | Induction Friendly",
      image: "/bronze-kadai.png",
      images: JSON.stringify(["/bronze-kadai.png"]),
      price: 1299,
      mrp: 1699,
      discount: 24,
      rating: 4.7,
      reviews: 87,
      categoryName: "kitchen-utility",
      material: "Steel",
      featured: false,
      stock: 14,
      vendorId: vendor.id
    },
    {
      name: "Tri-Ply Steel Saucepan",
      slug: "tri-ply-steel-saucepan",
      description: "Modern tri-ply stainless steel saucepan with glass lid for uniform heat distribution.",
      specs: "Capacity: 1.5 Litres | Tri-Ply",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 1499,
      mrp: 1999,
      discount: 25,
      rating: 4.8,
      reviews: 65,
      categoryName: "kitchen-utility",
      material: "Steel",
      featured: false,
      stock: 18,
      vendorId: null
    },
    {
      name: "Bronze Serving Bowl",
      slug: "bronze-serving-bowl",
      description: "Fine quality pure bronze serving bowl, perfect for traditional Indian curries.",
      specs: "Weight: 800g | Kansa Alloy",
      image: "/bronze-hero.png",
      images: JSON.stringify(["/bronze-hero.png"]),
      price: 1199,
      mrp: 1599,
      discount: 25,
      rating: 4.8,
      reviews: 41,
      categoryName: "kitchen-utility",
      material: "Bronze",
      featured: true,
      stock: 10,
      vendorId: vendor.id
    },
    {
      name: "Brass Mortar & Pestle",
      slug: "brass-mortar-pestle",
      description: "Heavy solid brass mortar and pestle for freshly grinding kitchen herbs and spices.",
      specs: "Weight: 1.2 kg | Solid Brass",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 899,
      mrp: 1199,
      discount: 25,
      rating: 4.9,
      reviews: 103,
      categoryName: "kitchen-utility",
      material: "Brass",
      featured: false,
      stock: 15,
      vendorId: null
    },

    // 12 Products for Brass Cookware
    {
      name: "Royal Brass Cookware Kadai",
      slug: "royal-brass-cookware-kadai",
      description: "Exquisite heavy-duty pure brass cooking kadai with dual handles.",
      specs: "Weight: 2.2 kg | Pure Brass",
      image: "/bronze-kadai.png",
      images: JSON.stringify(["/bronze-kadai.png"]),
      price: 2899,
      mrp: 3599,
      discount: 19,
      rating: 4.8,
      reviews: 54,
      categoryName: "brass-cookware",
      material: "Brass",
      featured: true,
      stock: 8,
      vendorId: vendor.id
    },
    {
      name: "Artisan Brass Patila Pot",
      slug: "artisan-brass-patila-pot",
      description: "Handcrafted deep brass cooking pot with flat bottom.",
      specs: "Capacity: 2 Litres | Pure Brass",
      image: "/bronze-hero.png",
      images: JSON.stringify(["/bronze-hero.png"]),
      price: 3599,
      mrp: 4299,
      discount: 16,
      rating: 4.6,
      reviews: 32,
      categoryName: "brass-cookware",
      material: "Brass",
      featured: true,
      stock: 5,
      vendorId: null
    },
    {
      name: "Classic Brass Degchi",
      slug: "classic-brass-degchi",
      description: "Deep heavy-gauge brass degchi pot designed specifically for slow biryani cooking.",
      specs: "Capacity: 4 Litres | Heavy Bottom",
      image: "/bronze-hero.png",
      images: JSON.stringify(["/bronze-hero.png"]),
      price: 4299,
      mrp: 5499,
      discount: 22,
      rating: 4.9,
      reviews: 45,
      categoryName: "brass-cookware",
      material: "Brass",
      featured: true,
      stock: 6,
      vendorId: vendor.id
    },
    {
      name: "Heavy-Gauge Brass Frying Pan",
      slug: "heavy-gauge-brass-frying-pan",
      description: "Premium heavy-gauge solid brass frypan with insulated handle.",
      specs: "Diameter: 22cm | Weight: 1.4 kg",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 2499,
      mrp: 3199,
      discount: 22,
      rating: 4.7,
      reviews: 38,
      categoryName: "brass-cookware",
      material: "Brass",
      featured: false,
      stock: 10,
      vendorId: vendor.id
    },
    {
      name: "Hand-Beaten Brass Saucepan",
      slug: "hand-beaten-brass-saucepan",
      description: "Sturdy hand-beaten brass pan with steel-coated handle for boiling water or milk.",
      specs: "Capacity: 1.5 Litres | Pure Brass",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 1999,
      mrp: 2699,
      discount: 26,
      rating: 4.8,
      reviews: 59,
      categoryName: "brass-cookware",
      material: "Brass",
      featured: false,
      stock: 14,
      vendorId: null
    },
    {
      name: "Traditional Brass Tadka Pan",
      slug: "traditional-brass-tadka-pan",
      description: "Specially designed small brass pan for quick tempering and spice roasting.",
      specs: "Weight: 600g | Heat Resistant Handle",
      image: "/bronze-kadai.png",
      images: JSON.stringify(["/bronze-kadai.png"]),
      price: 899,
      mrp: 1199,
      discount: 25,
      rating: 4.9,
      reviews: 74,
      categoryName: "brass-cookware",
      material: "Brass",
      featured: false,
      stock: 20,
      vendorId: vendor.id
    },
    {
      name: "Brass Steamer Pot",
      slug: "brass-steamer-pot",
      description: "Ornate brass steamer with stackable tiers for traditional dumpling or veggie steaming.",
      specs: "2-Tier | Weight: 2.8 kg",
      image: "/bronze-hero.png",
      images: JSON.stringify(["/bronze-hero.png"]),
      price: 3899,
      mrp: 4999,
      discount: 22,
      rating: 4.7,
      reviews: 28,
      categoryName: "brass-cookware",
      material: "Brass",
      featured: true,
      stock: 4,
      vendorId: null
    },
    {
      name: "Brass Handi with Lid",
      slug: "brass-handi-with-lid",
      description: "Splendid brass cooking pot complete with a matching lid to seal in flavors.",
      specs: "Capacity: 2.5 Litres | Pure Brass",
      image: "/bronze-hero.png",
      images: JSON.stringify(["/bronze-hero.png"]),
      price: 3199,
      mrp: 3999,
      discount: 20,
      rating: 4.8,
      reviews: 62,
      categoryName: "brass-cookware",
      material: "Brass",
      featured: false,
      stock: 11,
      vendorId: vendor.id
    },
    {
      name: "Royal Brass Tawa",
      slug: "royal-brass-tawa",
      description: "Heavy solid brass flat tawa pan for making rotis, parathas, and pancakes.",
      specs: "Diameter: 10 Inches | Weight: 1.8 kg",
      image: "/bronze-kadai.png",
      images: JSON.stringify(["/bronze-kadai.png"]),
      price: 1799,
      mrp: 2299,
      discount: 22,
      rating: 4.6,
      reviews: 49,
      categoryName: "brass-cookware",
      material: "Brass",
      featured: false,
      stock: 15,
      vendorId: vendor.id
    },
    {
      name: "Brass Rice Serving Pot",
      slug: "brass-rice-serving-pot",
      description: "Aesthetic brass serving vessel designed to keep rice warm and flavorful.",
      specs: "Capacity: 3 Litres | Hammered Finish",
      image: "/bronze-hero.png",
      images: JSON.stringify(["/bronze-hero.png"]),
      price: 2999,
      mrp: 3799,
      discount: 21,
      rating: 4.8,
      reviews: 35,
      categoryName: "brass-cookware",
      material: "Brass",
      featured: false,
      stock: 9,
      vendorId: null
    },
    {
      name: "Brass Soup Bowl",
      slug: "brass-soup-bowl",
      description: "Elegant, gold-colored solid brass soup bowl that holds temperature exceptionally well.",
      specs: "Capacity: 350ml | Weight: 300g",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 699,
      mrp: 899,
      discount: 22,
      rating: 4.5,
      reviews: 19,
      categoryName: "brass-cookware",
      material: "Brass",
      featured: false,
      stock: 30,
      vendorId: vendor.id
    },
    {
      name: "Handcrafted Brass Spoon Set",
      slug: "handcrafted-brass-spoon-set",
      description: "Set of 3 hand-chiseled pure brass spoons for serving lentils, rice, and gravy.",
      specs: "Set of 3 | Premium Brass Finish",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 499,
      mrp: 699,
      discount: 29,
      rating: 4.8,
      reviews: 80,
      categoryName: "brass-cookware",
      material: "Brass",
      featured: false,
      stock: 40,
      vendorId: null
    },

    // 12 Products for Pooja Collection
    {
      name: "Premium Brass Puja Thali Set",
      slug: "premium-brass-puja-thali-set",
      description: "Complete handcrafted puja thali with components for daily devotional ceremonies.",
      specs: "Material: Brass | 7 Pieces",
      image: "/collection-pooja.png",
      images: JSON.stringify(["/collection-pooja.png"]),
      price: 1899,
      mrp: 2499,
      discount: 24,
      rating: 4.8,
      reviews: 89,
      categoryName: "pooja-collection",
      material: "Brass",
      featured: true,
      stock: 12,
      vendorId: vendor.id
    },
    {
      name: "Hand-Hammered Copper Lota",
      slug: "hand-hammered-copper-lota",
      description: "Traditional copper vessel for prayer water and spiritual purification.",
      specs: "Material: Copper | 500ml",
      image: "/bronze-lota.png",
      images: JSON.stringify(["/bronze-lota.png"]),
      price: 899,
      mrp: 1299,
      discount: 31,
      rating: 4.9,
      reviews: 210,
      categoryName: "pooja-collection",
      material: "Copper",
      featured: true,
      stock: 15,
      vendorId: null
    },
    {
      name: "Sacred Brass Diya Lamp",
      slug: "sacred-brass-diya-lamp",
      description: "Exquisite traditional brass oil lamp (diya) with an elegant Peacock top handle.",
      specs: "Height: 6 Inches | Pure Brass",
      image: "/collection-pooja.png",
      images: JSON.stringify(["/collection-pooja.png"]),
      price: 499,
      mrp: 699,
      discount: 29,
      rating: 4.9,
      reviews: 130,
      categoryName: "pooja-collection",
      material: "Brass",
      featured: false,
      stock: 25,
      vendorId: vendor.id
    },
    {
      name: "Royal Kansa Pooja Bell",
      slug: "royal-kansa-pooja-bell",
      description: "Traditional hand-bell crafted with high-resonance bronze alloy for clear cosmic sound.",
      specs: "Weight: 450g | pure Bronze (Kansa)",
      image: "/collection-pooja.png",
      images: JSON.stringify(["/collection-pooja.png"]),
      price: 799,
      mrp: 999,
      discount: 20,
      rating: 4.8,
      reviews: 58,
      categoryName: "pooja-collection",
      material: "Bronze",
      featured: false,
      stock: 18,
      vendorId: vendor.id
    },
    {
      name: "Brass Ganesha Idol",
      slug: "brass-ganesha-idol",
      description: "Finely detailed solid brass idol of Lord Ganesha, perfect for your home altar or entrance.",
      specs: "Weight: 1.5 kg | Solid Brass",
      image: "/collection-pooja.png",
      images: JSON.stringify(["/collection-pooja.png"]),
      price: 1299,
      mrp: 1799,
      discount: 28,
      rating: 4.9,
      reviews: 77,
      categoryName: "pooja-collection",
      material: "Brass",
      featured: true,
      stock: 8,
      vendorId: null
    },
    {
      name: "Copper Panchpatra Set",
      slug: "copper-panchpatra-set",
      description: "Classic copper tumbler (patra) and spoon (achman) set used to distribute holy water.",
      specs: "Capacity: 250ml | Pure Copper",
      image: "/bronze-lota.png",
      images: JSON.stringify(["/bronze-lota.png"]),
      price: 649,
      mrp: 899,
      discount: 28,
      rating: 4.7,
      reviews: 42,
      categoryName: "pooja-collection",
      material: "Copper",
      featured: false,
      stock: 30,
      vendorId: vendor.id
    },
    {
      name: "Brass Incense Holder",
      slug: "brass-incense-holder",
      description: "Traditional hanging brass incenser with decorative cuts that vent aromatic smoke.",
      specs: "Weight: 500g | pure Brass",
      image: "/collection-pooja.png",
      images: JSON.stringify(["/collection-pooja.png"]),
      price: 549,
      mrp: 749,
      discount: 27,
      rating: 4.8,
      reviews: 33,
      categoryName: "pooja-collection",
      material: "Brass",
      featured: false,
      stock: 22,
      vendorId: vendor.id
    },
    {
      name: "Decorative Brass Aarti Plate",
      slug: "decorative-brass-aarti-plate",
      description: "Intricately hand-engraved deep-rimmed brass plate, specifically shaped for holding Aarti lamps.",
      specs: "Diameter: 10 Inches | Pure Brass",
      image: "/collection-pooja.png",
      images: JSON.stringify(["/collection-pooja.png"]),
      price: 1099,
      mrp: 1499,
      discount: 27,
      rating: 4.8,
      reviews: 51,
      categoryName: "pooja-collection",
      material: "Brass",
      featured: false,
      stock: 14,
      vendorId: null
    },
    {
      name: "Brass Shankh Stand",
      slug: "brass-shankh-stand",
      description: "Artistic brass stand to support the sacred conch shell on your prayer altar.",
      specs: "Weight: 350g | Intricate Detailing",
      image: "/collection-pooja.png",
      images: JSON.stringify(["/collection-pooja.png"]),
      price: 899,
      mrp: 1199,
      discount: 25,
      rating: 4.7,
      reviews: 26,
      categoryName: "pooja-collection",
      material: "Brass",
      featured: false,
      stock: 19,
      vendorId: vendor.id
    },
    {
      name: "Copper Water Kalash",
      slug: "copper-water-kalash",
      description: "Pure copper holy kalash pot with a hammered look, used for traditional ritual offerings.",
      specs: "Capacity: 1 Litre | Hand-Hammered",
      image: "/bronze-lota.png",
      images: JSON.stringify(["/bronze-lota.png"]),
      price: 1199,
      mrp: 1599,
      discount: 25,
      rating: 4.9,
      reviews: 69,
      categoryName: "pooja-collection",
      material: "Copper",
      featured: false,
      stock: 16,
      vendorId: vendor.id
    },
    {
      name: "Kansa Singing Bowl Set",
      slug: "kansa-singing-bowl-set",
      description: "High quality bronze singing bowl set with wooden mallet, ideal for meditation and prayer rooms.",
      specs: "Includes Wood Mallet & Cushion | Bronze",
      image: "/collection-pooja.png",
      images: JSON.stringify(["/collection-pooja.png"]),
      price: 2499,
      mrp: 3199,
      discount: 22,
      rating: 5.0,
      reviews: 95,
      categoryName: "pooja-collection",
      material: "Bronze",
      featured: true,
      stock: 5,
      vendorId: null
    },
    {
      name: "Antique Brass Camphor Burner",
      slug: "antique-brass-camphor-burner",
      description: "Artistic traditional brass camphor burner with wooden handle for offering prayers.",
      specs: "Length: 8 Inches | Wooden Handle",
      image: "/collection-pooja.png",
      images: JSON.stringify(["/collection-pooja.png"]),
      price: 599,
      mrp: 799,
      discount: 25,
      rating: 4.8,
      reviews: 48,
      categoryName: "pooja-collection",
      material: "Brass",
      featured: false,
      stock: 20,
      vendorId: vendor.id
    },

    // 12 Products for Copper Products
    {
      name: "Ayurvedic Pure Copper Water Bottle",
      slug: "ayurvedic-pure-copper-water-bottle",
      description: "Seamless leakproof joint-less copper bottle for natural Ayurvedic alkaline water storage.",
      specs: "Capacity: 1 Litre | Pure Copper",
      image: "/bronze-lota.png",
      images: JSON.stringify(["/bronze-lota.png"]),
      price: 999,
      mrp: 1399,
      discount: 29,
      rating: 4.9,
      reviews: 342,
      categoryName: "copper-products",
      material: "Copper",
      featured: true,
      stock: 20,
      vendorId: vendor.id
    },
    {
      name: "Traditional Copper Hammered Jug Set",
      slug: "traditional-copper-hammered-jug-set",
      description: "Elegant copper jug with two matching copper drinking glasses for the table.",
      specs: "1 Jug (1.5L) + 2 Glasses | Hammered",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 1899,
      mrp: 2499,
      discount: 24,
      rating: 4.7,
      reviews: 118,
      categoryName: "copper-products",
      material: "Copper",
      featured: true,
      stock: 12,
      vendorId: null
    },
    {
      name: "Seamless Copper Mug",
      slug: "seamless-copper-mug",
      description: "Charming hand-crafted copper mug, designed to keep cold drinks icy and fresh.",
      specs: "Capacity: 450ml | Lacquered Exterior",
      image: "/bronze-lota.png",
      images: JSON.stringify(["/bronze-lota.png"]),
      price: 599,
      mrp: 799,
      discount: 25,
      rating: 4.8,
      reviews: 67,
      categoryName: "copper-products",
      material: "Copper",
      featured: false,
      stock: 25,
      vendorId: vendor.id
    },
    {
      name: "Handcrafted Copper Carafe",
      slug: "handcrafted-copper-carafe",
      description: "Sleek handcrafted copper carafe with lid, designed for modern dining tables.",
      specs: "Capacity: 1.2 Litres | Pure Copper",
      image: "/bronze-lota.png",
      images: JSON.stringify(["/bronze-lota.png"]),
      price: 1499,
      mrp: 1999,
      discount: 25,
      rating: 4.6,
      reviews: 43,
      categoryName: "copper-products",
      material: "Copper",
      featured: false,
      stock: 15,
      vendorId: vendor.id
    },
    {
      name: "Engraved Copper Pitcher",
      slug: "engraved-copper-pitcher",
      description: "Stunning copper pitcher featuring traditional floral hand-engraving by Moradabad artisans.",
      specs: "Capacity: 2 Litres | Hand-Engraved",
      image: "/bronze-lota.png",
      images: JSON.stringify(["/bronze-lota.png"]),
      price: 1699,
      mrp: 2299,
      discount: 26,
      rating: 4.9,
      reviews: 88,
      categoryName: "copper-products",
      material: "Copper",
      featured: true,
      stock: 8,
      vendorId: null
    },
    {
      name: "Copper Wellness Glass Set",
      slug: "copper-wellness-glass-set",
      description: "Set of 4 pure copper drinking glasses designed to reap health benefits with every sip.",
      specs: "Set of 4 | Pure Copper",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 899,
      mrp: 1199,
      discount: 25,
      rating: 4.7,
      reviews: 52,
      categoryName: "copper-products",
      material: "Copper",
      featured: false,
      stock: 24,
      vendorId: vendor.id
    },
    {
      name: "Copper Hot Water Pot",
      slug: "copper-hot-water-pot",
      description: "Traditional kettle-like copper pot for storing and dispensing hot water.",
      specs: "Capacity: 3 Litres | Pure Copper",
      image: "/bronze-lota.png",
      images: JSON.stringify(["/bronze-lota.png"]),
      price: 2999,
      mrp: 3999,
      discount: 25,
      rating: 4.8,
      reviews: 31,
      categoryName: "copper-products",
      material: "Copper",
      featured: false,
      stock: 10,
      vendorId: vendor.id
    },
    {
      name: "Antique Copper Water Tank",
      slug: "antique-copper-water-tank",
      description: "Large size traditional copper water dispenser tank with brass tap.",
      specs: "Capacity: 8 Litres | Brass Tap Included",
      image: "/bronze-lota.png",
      images: JSON.stringify(["/bronze-lota.png"]),
      price: 4999,
      mrp: 6499,
      discount: 23,
      rating: 4.9,
      reviews: 79,
      categoryName: "copper-products",
      material: "Copper",
      featured: true,
      stock: 6,
      vendorId: null
    },
    {
      name: "Copper Serving Handi",
      slug: "copper-serving-handi",
      description: "Rustic double-walled serving pot with pure copper exterior and food-safe steel interior.",
      specs: "Steel-lined interior | pure Copper exterior",
      image: "/bronze-hero.png",
      images: JSON.stringify(["/bronze-hero.png"]),
      price: 1999,
      mrp: 2699,
      discount: 26,
      rating: 4.7,
      reviews: 46,
      categoryName: "copper-products",
      material: "Copper",
      featured: false,
      stock: 14,
      vendorId: vendor.id
    },
    {
      name: "Hammered Copper Bowl Set",
      slug: "hammered-copper-bowl-set",
      description: "Set of 3 stackable copper prep bowls with hammered aesthetic.",
      specs: "Set of 3 | Pure Copper",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 1299,
      mrp: 1699,
      discount: 24,
      rating: 4.6,
      reviews: 29,
      categoryName: "copper-products",
      material: "Copper",
      featured: false,
      stock: 18,
      vendorId: vendor.id
    },
    {
      name: "Copper Infused Yoga Bottle",
      slug: "copper-infused-yoga-bottle",
      description: "Sports copper bottle with protective carry sleeve, perfect for active lifestyle.",
      specs: "Includes Carry Sleeve | 1 Litre",
      image: "/bronze-lota.png",
      images: JSON.stringify(["/bronze-lota.png"]),
      price: 1099,
      mrp: 1499,
      discount: 27,
      rating: 4.8,
      reviews: 82,
      categoryName: "copper-products",
      material: "Copper",
      featured: false,
      stock: 22,
      vendorId: null
    },
    {
      name: "Designer Copper Bottle with Sleeve",
      slug: "designer-copper-bottle-with-sleeve",
      description: "Handcrafted copper bottle featuring beautiful geometric designs printed on the surface.",
      specs: "Capacity: 950ml | Joint-less design",
      image: "/bronze-lota.png",
      images: JSON.stringify(["/bronze-lota.png"]),
      price: 1299,
      mrp: 1799,
      discount: 28,
      rating: 4.8,
      reviews: 63,
      categoryName: "copper-products",
      material: "Copper",
      featured: false,
      stock: 15,
      vendorId: vendor.id
    },

    // 12 Products for Steel Essentials
    {
      name: "Premium Tri-Ply Stainless Steel Frypan",
      slug: "premium-tri-ply-stainless-steel-frypan",
      description: "High-grade commercial quality tri-ply stainless steel skillet for perfect sautéing.",
      specs: "Diameter: 24cm | Tri-Ply Steel",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 1499,
      mrp: 1999,
      discount: 25,
      rating: 4.8,
      reviews: 93,
      categoryName: "steel-essentials",
      material: "Steel",
      featured: true,
      stock: 12,
      vendorId: vendor.id
    },
    {
      name: "Durable Steel Storage Containers",
      slug: "durable-steel-storage-containers",
      description: "Airtight modular stainless steel kitchen organizer container set.",
      specs: "Set of 3 Containers | Airtight Lids",
      image: "/bronze-kadai.png",
      images: JSON.stringify(["/bronze-kadai.png"]),
      price: 799,
      mrp: 1099,
      discount: 27,
      rating: 4.6,
      reviews: 45,
      categoryName: "steel-essentials",
      material: "Steel",
      featured: true,
      stock: 18,
      vendorId: null
    },
    {
      name: "Double-Walled Steel Tiffin Box",
      slug: "double-walled-steel-tiffin-box",
      description: "Thermal insulated double-walled steel tiffin carrier to keep lunches hot.",
      specs: "3-Tier | Leak-Proof Locks",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 999,
      mrp: 1299,
      discount: 23,
      rating: 4.7,
      reviews: 70,
      categoryName: "steel-essentials",
      material: "Steel",
      featured: false,
      stock: 14,
      vendorId: vendor.id
    },
    {
      name: "Heavy-Gauge Steel Dinner Plates",
      slug: "heavy-gauge-steel-dinner-plates",
      description: "Set of 6 premium mirror-polished thick steel dinner plates.",
      specs: "Set of 6 | Mirror Finish",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 1199,
      mrp: 1599,
      discount: 25,
      rating: 4.8,
      reviews: 55,
      categoryName: "steel-essentials",
      material: "Steel",
      featured: false,
      stock: 22,
      vendorId: vendor.id
    },
    {
      name: "Steel Kitchen Organizer Rack",
      slug: "steel-kitchen-organizer-rack",
      description: "Heavy-duty double-tier stainless steel dish draining rack for kitchen counters.",
      specs: "Rust-Resistant Steel | Double Tier",
      image: "/bronze-kadai.png",
      images: JSON.stringify(["/bronze-kadai.png"]),
      price: 1899,
      mrp: 2499,
      discount: 24,
      rating: 4.9,
      reviews: 120,
      categoryName: "steel-essentials",
      material: "Steel",
      featured: true,
      stock: 8,
      vendorId: null
    },
    {
      name: "Multi-Utility Steel Spice Box",
      slug: "multi-utility-steel-spice-box",
      description: "Classic steel masala dabba with transparent see-through lid and 7 small cups.",
      specs: "Includes 7 Small Cups | Glass Lid",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 899,
      mrp: 1199,
      discount: 25,
      rating: 4.8,
      reviews: 62,
      categoryName: "steel-essentials",
      material: "Steel",
      featured: false,
      stock: 16,
      vendorId: vendor.id
    },
    {
      name: "Stainless Steel Mixing Bowl Set",
      slug: "stainless-steel-mixing-bowl-set",
      description: "Set of 5 heavy mixing and prep bowls with anti-skid silicone base.",
      specs: "Set of 5 Bowls | Silicone Bottom",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 1099,
      mrp: 1499,
      discount: 27,
      rating: 4.7,
      reviews: 43,
      categoryName: "steel-essentials",
      material: "Steel",
      featured: false,
      stock: 20,
      vendorId: vendor.id
    },
    {
      name: "Steel Water Jug",
      slug: "steel-water-jug",
      description: "Aesthetic steel jug with ice guard and smooth pouring spout.",
      specs: "Capacity: 2 Litres | Ice Guard Lip",
      image: "/bronze-lota.png",
      images: JSON.stringify(["/bronze-lota.png"]),
      price: 699,
      mrp: 899,
      discount: 22,
      rating: 4.6,
      reviews: 31,
      categoryName: "steel-essentials",
      material: "Steel",
      featured: false,
      stock: 25,
      vendorId: null
    },
    {
      name: "Stainless Steel Cutlery Set",
      slug: "stainless-steel-cutlery-set",
      description: "Set of 24 elegant stainless steel forks, knives, and spoons with premium organizer.",
      specs: "24-Piece Set | Cutlery Organizer Stand",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 1299,
      mrp: 1799,
      discount: 28,
      rating: 4.8,
      reviews: 84,
      categoryName: "steel-essentials",
      material: "Steel",
      featured: false,
      stock: 12,
      vendorId: vendor.id
    },
    {
      name: "Steel Tea Kettle",
      slug: "steel-tea-kettle",
      description: "Fast-boiling whistling tea kettle designed for gas and induction stove tops.",
      specs: "Capacity: 2.5 Litres | Whistle Spout",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 1599,
      mrp: 1999,
      discount: 20,
      rating: 4.7,
      reviews: 58,
      categoryName: "steel-essentials",
      material: "Steel",
      featured: false,
      stock: 15,
      vendorId: vendor.id
    },
    {
      name: "Stainless Steel Colander",
      slug: "stainless-steel-colander",
      description: "Professional grade micro-perforated steel strainer with solid handles.",
      specs: "Diameter: 28cm | Micro-perforated",
      image: "/bronze-kadai.png",
      images: JSON.stringify(["/bronze-kadai.png"]),
      price: 599,
      mrp: 799,
      discount: 25,
      rating: 4.8,
      reviews: 37,
      categoryName: "steel-essentials",
      material: "Steel",
      featured: false,
      stock: 30,
      vendorId: null
    },
    {
      name: "Double-Walled Steel Hot Case",
      slug: "double-walled-steel-hot-case",
      description: "Thermal hot pot casserole designed to keep flatbreads and rice fresh and steaming hot.",
      specs: "Capacity: 2 Litres | Insulated Lid",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 1399,
      mrp: 1899,
      discount: 26,
      rating: 4.8,
      reviews: 69,
      categoryName: "steel-essentials",
      material: "Steel",
      featured: false,
      stock: 16,
      vendorId: vendor.id
    },

    // 12 Products for Dinner Sets
    {
      name: "Vedic Bronze Thali Dinner Set",
      slug: "vedic-bronze-thali-dinner-set",
      description: "Exquisite pure bronze dinner set containing thali plates, bowls, glass, and spoon.",
      specs: "Kansa / Bronze | 6 Pieces",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 4999,
      mrp: 5999,
      discount: 17,
      rating: 4.9,
      reviews: 156,
      categoryName: "dinner-sets",
      material: "Bronze",
      featured: true,
      stock: 6,
      vendorId: vendor.id
    },
    {
      name: "Royal Brass Dinner Set",
      slug: "royal-brass-dinner-set",
      description: "Polished heavy solid brass royal dinner set for elite banqueting.",
      specs: "Brass | 5 Pieces",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 3899,
      mrp: 4599,
      discount: 15,
      rating: 4.8,
      reviews: 78,
      categoryName: "dinner-sets",
      material: "Brass",
      featured: true,
      stock: 10,
      vendorId: null
    },
    {
      name: "Elite Stainless Steel Dinner Set",
      slug: "elite-stainless-steel-dinner-set",
      description: "Highly polished luxury food-grade stainless steel dinnerware set.",
      specs: "Stainless Steel | 24 Pieces",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 2999,
      mrp: 3999,
      discount: 25,
      rating: 4.8,
      reviews: 83,
      categoryName: "dinner-sets",
      material: "Steel",
      featured: false,
      stock: 14,
      vendorId: vendor.id
    },
    {
      name: "Premium Kansa Thali Set",
      slug: "premium-kansa-thali-set",
      description: "Traditional pure Kansa dinnerware set hand-hammered to perfection by Moradabad artisans.",
      specs: "Pure Kansa | 6 Pieces",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 5499,
      mrp: 6999,
      discount: 21,
      rating: 4.9,
      reviews: 102,
      categoryName: "dinner-sets",
      material: "Bronze",
      featured: true,
      stock: 5,
      vendorId: vendor.id
    },
    {
      name: "Hand-Etched Brass Dinner Plate Set",
      slug: "hand-etched-brass-dinner-plate-set",
      description: "Stunning solid brass dinner plates with hand-etched borders.",
      specs: "Set of 2 Plates | Pure Brass",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 4599,
      mrp: 5999,
      discount: 23,
      rating: 4.8,
      reviews: 41,
      categoryName: "dinner-sets",
      material: "Brass",
      featured: false,
      stock: 12,
      vendorId: null
    },
    {
      name: "Deluxe Copper-Bottom Dinner Set",
      slug: "deluxe-copper-bottom-dinner-set",
      description: "Stainless steel dinnerware featuring copper-plated bottoms for heat retention.",
      specs: "Stainless Steel & Copper | 12 Pieces",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 4299,
      mrp: 5499,
      discount: 22,
      rating: 4.7,
      reviews: 35,
      categoryName: "dinner-sets",
      material: "Steel",
      featured: false,
      stock: 8,
      vendorId: vendor.id
    },
    {
      name: "Classic Steel Lunch Set",
      slug: "classic-steel-lunch-set",
      description: "Budget-friendly everyday dinner set in mirror-finish steel.",
      specs: "Stainless Steel | 6 Pieces",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 1599,
      mrp: 1999,
      discount: 20,
      rating: 4.6,
      reviews: 90,
      categoryName: "dinner-sets",
      material: "Steel",
      featured: false,
      stock: 25,
      vendorId: vendor.id
    },
    {
      name: "Traditional Bronze Bowl Set",
      slug: "traditional-bronze-bowl-set",
      description: "Set of 6 classic bronze soup and curry bowls.",
      specs: "Set of 6 | Kansa / Bronze",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 2199,
      mrp: 2799,
      discount: 21,
      rating: 4.9,
      reviews: 54,
      categoryName: "dinner-sets",
      material: "Bronze",
      featured: false,
      stock: 15,
      vendorId: null
    },
    {
      name: "Royal Golden Brass Dessert Bowls",
      slug: "royal-golden-brass-dessert-bowls",
      description: "Set of 4 brass dessert serving bowls with matching mini spoons.",
      specs: "4 Bowls + 4 Spoons | Pure Brass",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 1499,
      mrp: 1999,
      discount: 25,
      rating: 4.8,
      reviews: 39,
      categoryName: "dinner-sets",
      material: "Brass",
      featured: false,
      stock: 20,
      vendorId: vendor.id
    },
    {
      name: "Imperial Kansa Dinner Ware",
      slug: "imperial-kansa-dinner-ware",
      description: "Ultimate luxury handcrafted bronze banquet service for special occasions.",
      specs: "Premium Kansa | 8 Pieces Set",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 7999,
      mrp: 9999,
      discount: 20,
      rating: 5.0,
      reviews: 110,
      categoryName: "dinner-sets",
      material: "Bronze",
      featured: true,
      stock: 4,
      vendorId: null
    },
    {
      name: "Modern Matte Steel Plates",
      slug: "modern-matte-steel-plates",
      description: "Designer stainless steel plates featuring a modern matte finish.",
      specs: "Set of 4 | Matte Finish Steel",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 2499,
      mrp: 3199,
      discount: 22,
      rating: 4.7,
      reviews: 48,
      categoryName: "dinner-sets",
      material: "Steel",
      featured: false,
      stock: 16,
      vendorId: vendor.id
    },
    {
      name: "Vintage Brass Serving Platters",
      slug: "vintage-brass-serving-platters",
      description: "Set of 3 antique design brass platters for serving appetizers.",
      specs: "Set of 3 | Pure Brass",
      image: "/collection-tableware.png",
      images: JSON.stringify(["/collection-tableware.png"]),
      price: 2299,
      mrp: 2999,
      discount: 23,
      rating: 4.8,
      reviews: 57,
      categoryName: "dinner-sets",
      material: "Brass",
      featured: false,
      stock: 12,
      vendorId: vendor.id
    }
  ];

  for (const prod of products) {
    await prisma.product.create({
      data: {
        name: prod.name,
        slug: prod.slug,
        description: prod.description,
        specs: prod.specs,
        image: prod.image,
        images: JSON.parse(prod.images),
        price: prod.price,
        mrp: prod.mrp,
        discount: prod.discount,
        rating: prod.rating,
        reviews: prod.reviews,
        categoryName: prod.categoryName,
        material: prod.material,
        featured: prod.featured,
        stock: prod.stock,
        vendorId: prod.vendorId
      }
    });
  }
  console.log("Products seeded");

  // Seed a sample Inquiry for the vendor to see
  const seededProducts = await prisma.product.findMany({
    where: { vendorId: vendor.id }
  });

  await prisma.inquiry.create({
    data: {
      name: "David Miller",
      email: "david@millertraders.com",
      phone: "+1 415 555 2671",
      companyName: "Miller Import Traders",
      country: "United States",
      message: "We need urgent pricing quotes for bulk shipping of copper bottles and bronze Kadais to San Francisco port. Please send certificate of purity.",
      items: JSON.stringify(
        seededProducts.map(p => ({
          id: p.id,
          name: p.name,
          price: p.price,
          quantity: 50,
          material: p.material
        }))
      ),
      status: "PENDING"
    }
  });
  console.log("Sample B2B inquiry seeded for vendor");

  console.log("Seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
